### ISSUE TITLE
buildMetadata

### ISSUE THREAD

**Issue by jwilleke** [activescott/home-infra#1]
How is buildMetadata used in general and how are you using it?

As an example, in https://github.com/activescott/home-infra/blob/main/k8s/apps/plex/kustomization.yaml you show:
`buildMetadata: [originAnnotations, transformerAnnotations]`

And in https://github.com/activescott/home-infra/blob/main/k8s/apps/photoprism/kustomization.yaml
`buildMetadata: [managedByLabel, originAnnotations, transformerAnnotations]`

Previously it appears you only had `managedByLabel` which appears to be unset.

**Comment by activescott** [comment]
Each of these three values add additional metadata to the output resources about how they were generated. So when you’re browsing resources in k8s (in kubctl or k9s) you can figure out why they’re there. More detail at https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/buildmetadata/

**Comment by activescott** [comment]
As for why I added these no particular reason. Just playing around but I have found them useful to remind me about resources.
